/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package craigslist.clone;

import ch.vorburger.exec.ManagedProcessException;
import ch.vorburger.mariadb4j.DB;
import ch.vorburger.mariadb4j.DBConfigurationBuilder;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class AppTest {

    DB database = null;
    String url = null;

    @Before
    public void setupInMemoryDatabase() throws ManagedProcessException {
        DBConfigurationBuilder config = DBConfigurationBuilder.newBuilder();
        config.setPort(0);
        database = DB.newEmbeddedDB(config.build());

        url = config.getURL("test");
        database.start();

        // seed the database with the schema.
        database.source("schema.sql", "root", null, "test");
    }

    @After
    public void tearDownInMemoryDatabase() throws ManagedProcessException {
        database.stop();
    }

    @Test
    public void initiallyHasZeroOfEverything() throws SQLException {
        Connection conn = DriverManager.getConnection(url, "root", "");
        DBConnector connector = new DBConnector(conn);
        Assert.assertEquals(0, connector.getNumListings());
    }
}
