/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package craigslist.clone;

import io.javalin.Javalin;

public class App {

  public static void main(String[] args) {
    Javalin app = Javalin.create().start(7070);
    app.get("/", ctx -> ctx.result("Hello World"));
  }

}
